apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-classification-1
  labels:
    app: text-classification-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: text-classification-1
  template:
    metadata:
      labels:
        app: text-classification-1
    spec:
      containers:
      - name: text-classification-1
        image: text-classification-1:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          